#!/bin/bash

# Project:  World News Articles Matching
# File:     install
# Authors:  Jason Papapanagiotakis, Aris Kotsomitopoulos
# Github:   https://github.com/A-J-Thesis/Executable

sudo apt-get -y install git python-pip

git clone https://github.com/A-J-Thesis/Web-Article-Extractor.git
git clone https://github.com/A-J-Thesis/World-News-Articles-Matching.git

sudo pip install -U nltk

sudo apt-get -y install build-essential python-dev python-setuptools python-numpy python-scipy libatlas-dev libatlas3gf-base

pip install --user --install-option="--prefix=" -U scikit-learn

sudo pip install textblob

python < python_commands

sudo apt-get -y install python-bs4
sudo apt-get update
sudo apt-get -y install default-jre
sudo apt-get -y install default-jdk

